### ISSUE TITLE
Ver píldoras teóricas

### ISSUE THREAD

**Issue by MartaInes** [ISPP-G5/NexONG#116]
En esta issue se recoge el haber visto las píldoras teóricas de la semana 7 y 8.

**Comment by FranciscoRossoR** [comment]
Watched both week 7 theory pills.

**Comment by FelixoGudiel** [comment]
Watched both week 7 theory pills.

**Comment by claugp06** [comment]
Watched both theory pills

**Comment by marnunrey2** [comment]
Watched 1 theory pill from week 7

**Comment by manbarjim2** [comment]
Watched both week 7 theory pills.

**Comment by auroranavas** [comment]
Watched both theory pills

**Comment by fracalrod3** [comment]
Watching all theory pills

**Comment by manortbla** [comment]
Watched both week 7 theory pills.

**Comment by Ahydul** [comment]
Watched week 8 theory pill.

**Comment by manbarjim2** [comment]
Watched week 8 theory pill.

**Comment by MartaInes** [comment]
Watched week 7 and 8 theory pills

**Comment by auroranavas** [comment]
Watched week 8 pill

**Comment by fracalrod3** [comment]
Watched week 7 theory pills

**Comment by JuanluRM** [comment]
Watched week 7 and week 8 theory pills

**Comment by pedlopruz** [comment]
Watched week 7 and 8 theory pills

**Comment by FelixoGudiel** [comment]
Watched week 8 theory pills

**Comment by pabpercab1** [comment]
Watched theory pills

**Comment by marnunrey2** [comment]
Watched theory pill: Testing

**Comment by marnunrey2** [comment]
Watched theory pill: Customer agreement

**Comment by FranciscoRossoR** [comment]
Watched week 8 theory pill.
