### ISSUE TITLE
Anuncio

### ISSUE THREAD

**Issue by MartaInes** [ISPP-G5/NexONG#131]
Como en nuestro caso no tiene sentido hacer un storyboard dirigido a otro tipo de usuario, realizar un pequeño anuncio basándonos en el storyboard realizado la semana anterior.

**Comment by marnunrey2** [comment]
Este sprint cuento con mas de 65 horas, cuando solo debería tener entre 20 y 30 horas, por lo que veo mejor asignar esta tarea a otra persona con menos horas para que el trabajo sea equilibrado

**Comment by Ahydul** [comment]
I'm unable to correctly finish this issue. It'd be better if someone who has some experience in making or editing videos carries out this task.

**Comment by MartaInes** [comment]
It can be found as a release in the documentation project.

**Comment by pabpercab1** [comment]
**Story Points: 13**
  [See the discussion](https://action.parabol.co/meet/vuXFVDMk4E/estimate/1) in Docs S2 W8

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
