### ISSUE TITLE
Presentación Evaluación S2

### ISSUE THREAD

**Issue by MartaInes** [ISPP-G5/NexONG#139]
La presentación debe de recoger los siguientes aspectos:
- Killer opener
- Elevator pitch (Si procede)
- Resumen de análisis de competidores (Que nos diferencia?)
- Otro storyboard para rol distinto (Si no hay otro rol, se pasa a hacer vídeo)
- Impacto legal
- Customer agreement: Producto final, no desarrollo. Revisar documento con lo mínimo
- Resumen TCO
- Costes GitHub/GitHub actions
- Situación actual
- Estimaciones a corto, medio y largo plazo, justificando ingresos
- Refinamiento del equipo
- Estado comittement agreement
- Demo total del S2 --> Datos reales
- Retrospectiva
- Análisis de rendimiento
- Calidad de código
- Evolución de la calidad del código
- Como estamos midiendo las soluciones, a los problemas presentados
- Plan de usuarios pilotos
- Resumen de feedback recibido, como hemos manejado ese feedback
- Plan de gestion de usuarios pilotos del S3
- Comitement agreement con los usuarios pilotos
- Planificación del S3, o replanificación si procede
- Objetivos del S3 y demo del S3
- Si hace falta reestimar el alcance
- Reporte de IA
- Autodefensa
- Landing page

**Comment by marnunrey2** [comment]
I would change the red borders of the table according to the feedback received of not using the red color:
![image](https://github.com/ISPP-G5/NexONG/assets/73229261/1cb4c477-a868-41c1-94c5-c079a81c18fe)

**Comment by pabpercab1** [comment]
**Story Points: 21**
  [See the discussion](https://action.parabol.co/meet/vuXFVDMk4E/estimate/6) in Docs S2 W8

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
