### ISSUE TITLE
Realizar video demo del S2

### ISSUE THREAD

**Issue by MartaInes** [ISPP-G5/NexONG#145]
El video debe de hacer hincapié en los aspectos más importantes implementados durante el sprint, debe de verse todo claramente, haciendo zoom si fuese necesario y saltandose parte irrelevantes como el inicio de sesión.

**Comment by samrodman** [comment]
Hi, do you have an idea of the day this video should be recorded exactly? Thank you!

**Comment by MartaInes** [comment]
> Hi, do you have an idea of the day this video should be recorded exactly? Thank you!

Hey, It should be done once we have the deploy done. I think it was done yesterday, so you can do it anyday you want. Just remeber that it should only show the most important parts and it shouldn't be too long, so there's still enough time in the presentation to talk about everything.

**Comment by pabpercab1** [comment]
**Story Points: 5**
  [See the discussion](https://action.parabol.co/meet/vuXFVDMk4E/estimate/7) in Docs S2 W8

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
