### ISSUE TITLE
Presentación

### ISSUE THREAD

**Issue by MartaInes** [ISPP-G5/NexONG#195]
Esta semana la presentación debe de contener los puntos recogidos en la discusión de esta semana:
- https://github.com/orgs/ISPP-G5/discussions/187

**Comment by pabpercab1** [comment]
**Story Points: 21**
  [See the discussion](https://action.parabol.co/meet/vS672cyxOM/estimate/10) in Docs S3

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
