### ISSUE TITLE
Time-Effort-report

### ISSUE THREAD

**Issue by MartaInes** [ISPP-G5/NexONG#199]
En este documento debe estar recogido el esfuerzo del equipo medido a través del clockify. Si se ve que en md no queda bien el formato, se puede crear un archivo Time-Effort-report.md con su portada correspondiente, que redireccioné al pdf generado.

**Comment by pabpercab1** [comment]
**Story Points: 1**
  [See the discussion](https://action.parabol.co/meet/vS672cyxOM/estimate/21) in Docs S3

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
