### ISSUE TITLE
Evaluación de Rendimiento

### ISSUE THREAD

**Issue by MartaInes** [ISPP-G5/NexONG#200]
Seguir la plantilla proporcionado en EV para el PerformanceEvaluation.md, donde deben de verse reflejadas las notas del sprint.

**Comment by pabpercab1** [comment]
**Story Points: 3**
  [See the discussion](https://action.parabol.co/meet/vS672cyxOM/estimate/17) in Docs S3

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
