### ISSUE TITLE
Usuarios Piloto

### ISSUE THREAD

**Issue by MartaInes** [ISPP-G5/NexONG#201]
Es este documento, titulado "pilots.md" debe quedar recogido el estado, plan, y gestión del feedback de los usuarios pilotos.

**Comment by auroranavas** [comment]
We will also update both feedback forms.

**Comment by pabpercab1** [comment]
**Story Points: 2**
  [See the discussion](https://action.parabol.co/meet/vS672cyxOM/estimate/15) in Docs S3

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
