### ISSUE TITLE
Rendimiento de los Usuarios Piloto

### ISSUE THREAD

**Issue by MartaInes** [ISPP-G5/NexONG#203]
En el documento "PilotUsersPerformanceEvaluation.md", cuya plantilla se puede encontrar en la EV, debe de recogerse nuestra opinión sobre la labor que han desempeñado los del grupo 11 como usuarios piloto en este tercer sprint.

**Comment by pabpercab1** [comment]
**Story Points: 3**
  [See the discussion](https://action.parabol.co/meet/vS672cyxOM/estimate/20) in Docs S3

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
