### ISSUE TITLE
FC terms review

### ISSUE THREAD

**Issue by MartaInes** [ISPP-G5/NexONG#205]
Las personas asignadas a esta tarea deben de revisar las Failure Conditions que se detallan en el documento de la EV. ADEMÁS, deben de recordar registrar ese tiempo bajo el nombre "FC terms review" en el clockify.

**Comment by pabpercab1** [comment]
**Story Points: 8**
  [See the discussion](https://action.parabol.co/meet/vS672cyxOM/estimate/19) in Docs S3

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
