### ISSUE TITLE
Deployed Software review

### ISSUE THREAD

**Issue by MartaInes** [ISPP-G5/NexONG#206]
Las personas asignadas a esta tarea deben de revisar el "Software Reviewer Guidelines" de la EV, y asegurarse de que se cumplen todos los puntos, teniendo así que crear un documento "revision.md". ADEMÁS, deben de recordar registrar ese tiempo bajo el nombre "Deployed Software review" en el clockify.

**Comment by pabpercab1** [comment]
**Story Points: 5**
  [See the discussion](https://action.parabol.co/meet/vS672cyxOM/estimate/16) in Docs S3

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
