### ISSUE TITLE
Expected aspects review

### ISSUE THREAD

**Issue by MartaInes** [ISPP-G5/NexONG#207]
Las personas asignadas a esta tarea deben de revisar que la presentación contiene todos los puntos que se habían pedido. ADEMÁS, deben de recordar registrar ese tiempo bajo el nombre "Expected aspects review" en el clockify.

**Comment by pabpercab1** [comment]
**Story Points: 5**
  [See the discussion](https://action.parabol.co/meet/vS672cyxOM/estimate/18) in Docs S3

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
