### ISSUE TITLE
Watch Theoy Pill on GDPR and UX

### ISSUE THREAD

**Issue by MartaInes** [ISPP-G5/NexONG#212]
Todo el mundo debe de ver la píldora teórica que se encuentra en la carpeta Week9 en EV. 

RECORDAD registrar esto en clockify en el apartado de píldoras bajo el nombre "**watch_theory_pill_on_GDPR_and_UX**"

**Comment by claugp06** [comment]
Watch the theory pill of week 9. Several aspesct regarding the GDPR should be include in ou project.

**Comment by FelixoGudiel** [comment]
Watch the theory pill of week 9

**Comment by samrodman** [comment]
Watched the theory pill of week 9

**Comment by JuanluRM** [comment]
Watched the theory pill of week 9: Theoy Pill on GDPR and UX

**Comment by manbarjim2** [comment]
Watched the theory pill of week 9: Theoy Pill on GDPR and UX

**Comment by manortbla** [comment]
Watched the theory pill of week 9

**Comment by Ahydul** [comment]
Watched the theory pill of week 9

**Comment by MartaInes** [comment]
Watched week 9 theory pill

**Comment by pedlopruz** [comment]
Watched week 9 theory pill

**Comment by marnunrey2** [comment]
Watched the theory pill of week 9: Theoy Pill on GDPR and UX

**Comment by pabpercab1** [comment]
Watched the theory pill of week 9
