### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by MartaInes** [ISPP-G5/NexONG#217]
En este documentos deben de registrarse los cambios realizados en el S3 dividiéndolo en:
- Incrementos (Features)
- Mejoras (Improvements)
- Arreglos (Fixes)

**Comment by pabpercab1** [comment]
**Story Points: 3**
  [See the discussion](https://action.parabol.co/meet/wf6jPlwJUc/estimate/1) in Docs S3 v2

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
