### ISSUE TITLE
Hacer de Usuario Piloto

### ISSUE THREAD

**Issue by MartaInes** [ISPP-G5/NexONG#235]
Probar y puntuar la aplicación del Grupo 11 (Aparking)

**Comment by marnunrey2** [comment]
Already tested their prototype

**Comment by pedlopruz** [comment]
Prototype tested

**Comment by MRomalde** [comment]
Already tested the prototype!

**Comment by pabpercab1** [comment]
**Story Points: 5**
  [See the discussion](https://action.parabol.co/meet/wmfXZlCZyg/estimate/5) in Docs PPL

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by manortbla** [comment]
Already tested their prototype

**Comment by ivaramlar** [comment]
Already tested the prototype!

**Comment by FranciscoRossoR** [comment]
Tested Aparking prototype.

**Comment by FelixoGudiel** [comment]
Already tested their prototype
