### ISSUE TITLE
Marketing Plan

### ISSUE THREAD

**Issue by MartaInes** [ISPP-G5/NexONG#258]
El Plan de Marketing tiene que contener las siguientes cosas:
- Modelo de segmentación del mercado, caracterización de la audiencia (al menos con dos perfiles)
- Palabras claves y optimización en navegadores
- Campaña de lanzamiento a corto plazo
> - Publicaciones previstas
> - Tiempos entre publicaciones
> - Estudio de cual es la mejor hora/día para hacer las publicaciones
- Resultado que se espera con las redes sociales y en cuanto tiempo

Para este documento recomiendo ver primero la última píldora teórica.
Además como es un documento con varios puntos, para mayor productividad recomendaría también dividir el trabajo, pero siempre intentando que el resultado final sea coherente.

**Comment by pabpercab1** [comment]
**Story Points: 8**
  [See the discussion](https://action.parabol.co/meet/wmfXZlCZyg/estimate/9) in Docs PPL

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
