### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by MartaInes** [ISPP-G5/NexONG#260]
Debe realizarse una demo para enseñar el producto final, en esta deben destacarse las funcionalidades más importantes y que nos caracterizan, así como deben de verse bien reflejados los distintos roles y sus funcionalidades. A través de la demo, una persona que no sepa nada del proyecto debe de ser capaz de entender de qué va.

**Comment by pabpercab1** [comment]
**Story Points: 8**
  [See the discussion](https://action.parabol.co/meet/wmfXZlCZyg/estimate/4) in Docs PPL

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
