### ISSUE TITLE
Presentación semana 11

### ISSUE THREAD

**Issue by MartaInes** [ISPP-G5/NexONG#263]
Debe de incluir las siguientes cosas:
- 10 min (Ensayo WPL)
	- de que va el proyecto: killer opener/video usuario-cliente/demo/competencia
	- quien hay detras: equipo
	- es rentable el proyecto: plan de negocios/tco/anuncio para inversores(filantropos)
	- donde puedo ver más información
- 5 min Marketing
	- Plan de marketing
	- Modelo segmentación del mercado, caracterización de la audiencia (al menos dos perfiles)
	- Optimización en buscadores, palabras clave
	- Campaña de lanzamiento a corto plazo (videos/fotos con la ONG) --> feedback de la ONG
	- Community Management: objetivos y planning en las redes sociales, numero de impresiones que se busca.
	- Uso de la IA

**Comment by pabpercab1** [comment]
**Story Points: 13**
  [See the discussion](https://action.parabol.co/meet/wmfXZlCZyg/estimate/12) in Docs PPL

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
