### ISSUE TITLE
AI Usage

### ISSUE THREAD

**Issue by MartaInes** [ISPP-G5/NexONG#264]
Se debe seguir con el seguimiento a través del excel y recogiendo todos los resultados en el documento correspondiente.

**Comment by pabpercab1** [comment]
**Story Points: 3**
  [See the discussion](https://action.parabol.co/meet/wmfXZlCZyg/estimate/1) in Docs PPL

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
