### ISSUE TITLE
Mejorar anuncio

### ISSUE THREAD

**Issue by MartaInes** [ISPP-G5/NexONG#265]
Seguir el feedback dado en clase para perfeccionar el último anuncio

**Comment by pabpercab1** [comment]
**Story Points: 13**
  [See the discussion](https://action.parabol.co/meet/wASAT4jqEw/estimate/9) in Docs PPL v2

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by pabpercab1** [comment]
**Story Points: 13**
  [See the discussion](https://action.parabol.co/meet/wJlq7dePMk/estimate/3) in WPL

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
