### ISSUE TITLE
BCC

### ISSUE THREAD

**Issue by MartaInes** [ISPP-G5/NexONG#266]
Subir el feedback a la base de conocimientos común y en nuestro documento report.md, así como mencionar en dicho documento el cómo hacemos uso de ese feedback.

**Comment by pabpercab1** [comment]
**Story Points: 1**
  [See the discussion](https://action.parabol.co/meet/wmfXZlCZyg/estimate/3) in Docs PPL

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
