### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by MartaInes** [ISPP-G5/NexONG#267]
Mejorar el diseño de la Landing Page, así como añadir toda la información pertinente sobre nosotros, nuestra forma de tratar la información, y cualquier otra información que sea significativa.

**Comment by pabpercab1** [comment]
**Story Points: 5**
  [See the discussion](https://action.parabol.co/meet/wmfXZlCZyg/estimate/7) in Docs PPL

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
