### ISSUE TITLE
Revisar evaluaciones anteriores

### ISSUE THREAD

**Issue by MartaInes** [ISPP-G5/NexONG#269]
Revisar desde el DP hasta el S3, individualmente las notas si se han hecho acorde las métricas. Y cambiar algunas anteriores como resultado de las discusiones individuales.

**Comment by pabpercab1** [comment]
**Story Points: 8**
  [See the discussion](https://action.parabol.co/meet/wmfXZlCZyg/estimate/15) in Docs PPL

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
