### ISSUE TITLE
Plan de negocios

### ISSUE THREAD

**Issue by MartaInes** [ISPP-G5/NexONG#271]
Se debe recoger nuestro plan de negocios modificado, añadiendo además aspectos para ver si es rentable o no, y estudiar si nuestro proyecto sería atractivo para posibles inversores (teniendo en cuenta que trabajamos con ONGs, por lo que tal vez estos inversores serían más ayudas, o filántropos)

**Comment by pabpercab1** [comment]
**Story Points: 8**
  [See the discussion](https://action.parabol.co/meet/wmfXZlCZyg/estimate/10) in Docs PPL

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
