### ISSUE TITLE
Watch Theory pill on market segmentation, traction, and community management

### ISSUE THREAD

**Issue by MartaInes** [ISPP-G5/NexONG#274]
Recordad comentar en la issue una vez que la veais y registrar las horas en el clockify con su nombre correspondiente.

**Comment by FelixoGudiel** [comment]
Watched the week 12 theory pills on market segmentation, traction, and community management.

**Comment by manbarjim2** [comment]
Watched the week 12 theory pills on market segmentation, traction, and community management.

**Comment by samrodman** [comment]
Watched the week 12 theory pills on market segmentation, traction, and community management.

**Comment by FranciscoRossoR** [comment]
Watched the week 12 theory pill on market segmentation, traction, and community management.

**Comment by ivaramlar** [comment]
Watched the week 12 theory pills on market segmentation, traction, and community management.

**Comment by manortbla** [comment]
Watched the week 12 theory pills on market segmentation, traction, and community management.

**Comment by pedlopruz** [comment]
Watched the week 12 theory pills on market segmentation, traction, and community management.

**Comment by marnunrey2** [comment]
Watched the week 12 theory pills on market segmentation, traction, and community management.

**Comment by claugp06** [comment]
Wtched week 12 theory pill

**Comment by Ahydul** [comment]
Watched week 12 theory pill

**Comment by pabpercab1** [comment]
Watched week 12 theory pill
