### ISSUE TITLE
Documentación del proyecto

### ISSUE THREAD

**Issue by MartaInes** [ISPP-G5/NexONG#278]
En este documento deben de incluirse las cosas que se tenían previstas y que han quedado por hacer, cosas que se pueden mejorar, así como las tareas que se han realizado. Para que de esta manera sea más fácil para la gente del año que viene retomar nuestro trabajo.

**Comment by claugp06** [comment]
@pabpercab1 Si te parece bien, ¿creamos una misma estrcutura para ambos documentos para facilitar su lectura?

**Comment by pabpercab1** [comment]
> @pabpercab1 Si te parece bien, ¿creamos una misma estrcutura para ambos documentos para facilitar su lectura?

Por mi perfecto @claugp06

**Comment by pabpercab1** [comment]
**Story Points: 13**
  [See the discussion](https://action.parabol.co/meet/wASAT4jqEw/estimate/4) in Docs PPL v2

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
