### ISSUE TITLE
Publicaciones RRSS

### ISSUE THREAD

**Issue by MartaInes** [ISPP-G5/NexONG#323]

**Comment by manbarjim2** [comment]
Todos los post de esta semana han sido programados

**Comment by pabpercab1** [comment]
**Story Points: 8**
  [See the discussion](https://action.parabol.co/meet/wJlq7dePMk/estimate/6) in WPL

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
