### ISSUE TITLE
Análisis de costes

### ISSUE THREAD

**Issue by pabpercab1** [ISPP-G5/NexONG#59]
GitHub actions → Estimar tiempo para estimar costes
Github o github actions --> Calcular precio con estimaciones y con personas

**Comment by pedlopruz** [comment]
Al revisar el documento no he encontrado ningun error acerca del contenido, lo unico es un apunte al principio del mismo sin importancia, por lo demás todo correcto

**Comment by pedlopruz** [comment]
Solucionado
