### ISSUE TITLE
Matriz RACI

### ISSUE THREAD

**Issue by MartaInes** [ISPP-G5/NexONG#89]
La matriz debe de contener las responsabilidades actualizadas y teniendo en cuenta lo roles de revisores, asignados, team leader y PM.

**Comment by manortbla** [comment]
Just a few changes to make the document perfect:

-  In 'devising a project,' you should write Sprint 2. 
-  Include the legends for the RACI matrix..

**Comment by pedlopruz** [comment]
Thanks for comment, changes are applied

**Comment by manortbla** [comment]
Perfect, good job.

**Comment by pabpercab1** [comment]
**Story Points: 5**
  [See the discussion](https://action.parabol.co/meet/v92d9uc3T2/estimate/19) in Docs S2

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
