### ISSUE TITLE
Customer Agreement

### ISSUE THREAD

**Issue by MartaInes** [ISPP-G5/NexONG#94]
Debe de ser un acuerdo legal entre nosotros y nuestro cliente que señales los términos y condiciones de la relación. Este acuerdo debe de seguir las pautas explicadas en su respectiva píldora teórica. Este acuerdo sería para establecer la relación entre nosotros y un cliente al que le ofrecemos nuestra solución software ya implementada (no confundir con el Development Agreement).

**Comment by pabpercab1** [comment]
**Story Points: 8**
  [See the discussion](https://action.parabol.co/meet/v92d9uc3T2/estimate/10) in Docs S2

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
