### ISSUE TITLE
Base de datos común (W7)

### ISSUE THREAD

**Issue by MartaInes** [ISPP-G5/NexONG#97]
Añadir el feedback dado en la semana al docusaurus de la asignatura, además de recogerlo en el documento 5-report.

**Comment by manortbla** [comment]
Good job adding last week's feedback to the common database, but you still need to update the 5-Report.md document and add it to the Sprint 2 folder.

**Comment by pabpercab1** [comment]
**Story Points: 5**
  [See the discussion](https://action.parabol.co/meet/v92d9uc3T2/estimate/7) in Docs S2

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
