### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by MartaInes** [ISPP-G5/NexONG#99]
Mejora de la Landing Page ya existente:
- Quitar el enlace del logo y poner un apartado donde puedan aparecer las distintas versiones de nuestro proyecto, así como sus respectivos formularios de evaluación. 
- Añadir información sobre la ONG y su cometido
-  Mejorar el estilo:
> - Formas circulares en las fotos del equipo
> - Usar una estética y estructura más clásica de landing page como la que se puede ver en estos ejemplos (https://unbounce.com/landing-page-examples/best-landing-page-examples/) En esta página se dan además consejos de como hacer una buena landing page

Añadir también en un footer todos los aspectos legales, que se recogen en el documento de Impacto Legal, para ser completamente transparentes en cuanto al uso de datos.

**Comment by pabpercab1** [comment]
**Story Points: 3**
  [See the discussion](https://action.parabol.co/meet/v92d9uc3T2/estimate/5) in Docs S2

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by MartaInes** [comment]
I was reviewing the landing page and it has improved a lot, but there are still some things that could be improve:
- The logotype disappears a bit with the blue background
- It's a bit confusing that the information squares change of colour whrn passing by, it looks like they are clickable
- When you go to one of the pages on the side menu, the side menu stops working, it only allows you to go back to the main page

**Comment by fracalrod3** [comment]
I'll change the first two things, but about the side menu, I've tried It both on phone and PC and It works
